# version: '3'

networks:
    iae_shared_network:
        external: true

services:
    user_web:
        build:
            context: ./
            dockerfile: docker/dev/web.docker
        container_name: user_nginx
        # ports:
        #     - "8084:80"
        volumes:
            - ./:/var/www
        depends_on:
            - user_app
        environment:
            - VIRTUAL_HOST=api.user.test
        networks:
            - iae_shared_network

    user_app:
        build:
            context: ./
            dockerfile: docker/dev/app.docker
        container_name: user_app
        volumes:
            - ./:/var/www
        depends_on:
            - user_db
            - user_cache
        environment:
            - REDIS_PORT=6379
            - REDIS_HOST=user_cache
            - DB_CONNECTION=mysql
            - DB_HOST=user_db
            - DB_PORT=3306
            - DB_DATABASE=db_user
            - DB_USERNAME=root
            - DB_PASSWORD=123
        networks:
            - iae_shared_network

    user_db:
        image: mysql:8.2
        container_name: user_db
        environment:
            - MYSQL_ROOT_PASSWORD=123
            - MYSQL_DATABASE=db_user
        ports:
            - "3307:3306"
        volumes:
            - user_data:/var/lib/mysql
        networks:
            - iae_shared_network

    user_cache:
        image: redis:latest
        container_name: user_cache
        ports:
            - "63795:6379"
        networks:
            - iae_shared_network

    user_phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: user_phpmyadmin
        depends_on:
            - user_db
            - user_cache
        environment:
            - PMA_HOST=user_db
            - PMA_USER=root
            - PMA_PASSWORD=123
            - VIRTUAL_HOST=pma.user.test
        ports:
            - "8081:80"
        networks:
            - iae_shared_network

volumes:
    user_data: