# version: '3'

networks:
    iae_shared_network:
        external: true

services:
    user_nginx_proxy:
        image: jwilder/nginx-proxy
        container_name: user_nginx_proxy
        ports:
            - "8089:80"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        networks:
            - iae_shared_network

    user_web:
        build:
            context: ./
            dockerfile: docker/dev/web.docker
        container_name: user_nginx
        # ports:
        #     - "8084:80"
        volumes:
            - ./:/var/www
        depends_on:
            - user_app
        environment:
            - VIRTUAL_HOST=api.user.test
        networks:
            - iae_shared_network

    user_app:
        build:
            context: ./
            dockerfile: docker/dev/app.docker
        container_name: user_app
        volumes:
            - ./:/var/www
        depends_on:
            - user_db
            - user_cache
        environment:
            - REDIS_PORT=6379
            - REDIS_HOST=user_cache
        networks:
            - iae_shared_network

    user_db:
        image: mysql:8.2
        container_name: user_db
        environment:
            - MYSQL_ROOT_PASSWORD=123
            - MYSQL_DATABASE=db_user
        ports:
            - "33066:3306"
        volumes:
            - user_data:/var/lib/mysql
        networks:
            - iae_shared_network

    user_cache:
        image: redis:latest
        container_name: user_cache
        ports:
            - "63796:6379"
        networks:
            - iae_shared_network

    user_phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: user_phpmyadmin
        depends_on:
            - user_db
        environment:
            - PMA_HOST=user_db
            - PMA_USER=root
            - PMA_PASSWORD=123
            - VIRTUAL_HOST=pma.user.test
        networks:
            - iae_shared_network

volumes:
    user_data: