# Gunakan image PHP dengan Apache
FROM php:8.1-apache

# Install dependencies untuk Laravel
RUN apt-get update && apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev git unzip && \
    docker-php-ext-configure gd --with-freetype --with-jpeg && \
    docker-php-ext-install gd

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Set Working Directory
WORKDIR /var/www/html

# Copy file Laravel ke container
COPY . .

# Install dependencies Laravel dengan Composer
RUN composer install

# Expose port 80 untuk akses HTTP
EXPOSE 80
